### ISSUE TITLE
Game crashing during Mountain Pass Mission

### ISSUE THREAD

**Issue by nicozagi** [HerzogAndrean/SHKR#1]
Hey, 

First off, thank you for making these. These remastered maps are fun.
I'm having a very strange issue with the Mountain Pass mission against the pig.

The game crashes every time right after the wolfs are spawned in the southern part of the map. I believe it's after the thrid attack wave.

The first time, I thought I was just unlucky and the game crashed but it did never crash before. I didn't have a savegame either so I restarted the mission and saved multiple times.

Not sure what causes it. I will look into it once I have more time. Here is the savegame if you want to check it out. You could let me know if the game crashes on your PC as well: https://www.dropbox.com/s/j6ers6jhg44pr1q/mountainpass_crash.sav?dl=0

Thanks again,

-nicozagi

PS: Ace move with the quarry behind the wall. I only just discovered it haha

**Comment by HerzogAndrean** [comment]
Thanks for reporting!

After some tests I know the reason behind the crash.
The cause is the killing of the last deer (lower right corner of the map). That alone or in combination with an event in May 1192 may cause it to crash. So, to prevent the crash you just have to stop your hunters. Then you can also use your savefile.

Hope I could help.

**Comment by nicozagi** [comment]
Thanks mate,

Hunters were pretty useless at the end since the crash happened again after I waited some time.

Finishing this map I have to say that it was fun but at very hard not that big of a challenge. Especially after I found out that there is stone to mine.

My recommendations if you would like to make the mission harder would be:

- remove the option to mine stone but leave something like 40 stone in the storage
- remove some of the iron fields, I got it faster than I could sell it
- add a fire event during the last siege
- maybe even more wolfs
- hop farm event that destroy crops
- remove the middle stone bridge to increase time wood comes to storage
- event that thieves took food
- larger siege armies
- make it impossible to build towers too near to the sign post

Still, great work so thank you for making these. 

I can recommend these maps to you for further inspiration: https://stronghold.heavengames.com/downloads/lister.php?category=sh_invasions&author=PrinceofHesse

His maps are beautiful and realistic just like yours.

-nicozagi
